### ISSUE TITLE
Cannot use deec_cci_all

### ISSUE THREAD

**Issue by XinyeZhao** [ZJUFanLab/SpaTalk#1]
Hi,
When I run the scripts and it pops an error for dec_cci_all method
![image](https://user-images.githubusercontent.com/92811944/164480789-537925a3-1c76-4241-9a5f-201424bcd164.png)
It says "receptor_tf" not found.

Can you tell me how to fix this?

**Comment by multitalk** [comment]
Hello, I have fixed this by revising the code of `dec_cci_all`. You can re-install the packgae and try it. Please feel free to contact me  if there are other bugs. Thanks a lot.
