### ISSUE TITLE
problem: dec_cci and dec_cci_all

### ISSUE THREAD

**Issue by jinyuanchun** [ZJUFanLab/SpaTalk#10]
Hi, When I used dec_cci and dec_cci_all to analysis  my data about cell-cell communications 
 and it pops  errors
dec_cci error ：
```
Error in intI(j, n = d[2L], dn[[2L]], give.dn = FALSE): invalid character indexing
Traceback:

1. dec_cci(object = obj, celltype_sender = "Vascular", celltype_receiver = "Differentiated_like", 
 .     use_n_cores = 4)
2. .lr_distance_doParallel(st_data, cell_pair, lrdb, celltype_sender, 
 .     celltype_receiver, per_num, pvalue)
3. st_data[lrdb$ligand, cell_pair$cell_sender]
4. st_data[lrdb$ligand, cell_pair$cell_sender]
5. callGeneric(x, i = i, j = j, drop = TRUE)
6. eval(call, parent.frame())
7. eval(call, parent.frame())
8. x[i = i, j = j, drop = TRUE]
9. x[i = i, j = j, drop = TRUE]
10. subCsp_ij(x, i, j, drop = drop)
11. intI(j, n = d[2L], dn[[2L]], give.dn = FALSE)
12. stop("invalid character indexing")
```
dec_cci_all error
Note: there are 6 cell types and 30 pair-wise cell pairs 
Begin to find LR pairs 
Error in {: task 1 failed - "invalid character indexing"
Traceback:

1. dec_cci_all(object = obj, use_n_cores = 4)
2. foreach::foreach(i = 1:nrow(celltype_pair), .packages = c("Matrix", 
 .     "reshape2"), .export = c(".get_cellpair", ".lr_distance", 
 .     ".get_tf_res", ".get_score")) %dopar% {
 .     celltype_sender <- celltype_pair$celltype_sender[i]
 .     celltype_receiver <- celltype_pair$celltype_receiver[i]
 .     cell_pair <- .get_cellpair(celltype_dist, st_meta, celltype_sender, 
 .         celltype_receiver, n_neighbor)
 .     cell_sender <- st_meta[st_meta$celltype == celltype_sender, 
 .         ]
 .     cell_receiver <- st_meta[st_meta$celltype == celltype_receiver, 
 .         ]
 .     cell_pair_all <- nrow(cell_sender) * nrow(cell_receiver)/2
 .     if (nrow(cell_pair) > min_pairs) {
 .         if (nrow(cell_pair) > cell_pair_all * min_pairs_ratio) {
 .             lrdb <- object@lr_path$lrpairs
 .             lrdb <- .lr_distance(st_data, cell_pair, lrdb, celltype_sender, 
 .                 celltype_receiver, per_num, pvalue)
 .             max_hop <- object@para$max_hop
 .             receptor_tf <- NULL
 .             if (nrow(lrdb) > 0) {
 .                 receptor_tf <- .get_tf_res(celltype_sender, celltype_receiver, 
 .                   lrdb, ggi_tf, cell_pair, st_data, max_hop, 
 .                   co_exp_ratio)
 .                 if (!is.null(receptor_tf)) {
 .                   lrdb <- .get_score(lrdb, receptor_tf)
 .                 }
 .                 else {
 .                   lrdb <- NULL
 .                 }
 .             }
 .             if (is.data.frame(lrdb)) {
 .                 if (nrow(lrdb) > 0) {
 .                   list(lrdb = lrdb, receptor_tf = receptor_tf, 
 .                     cell_pair = cell_pair)
 .                 }
 .             }
 .         }
 .     }
 . }
3. e$fun(obj, substitute(ex), parent.frame(), e$data)

**Comment by multitalk** [comment]
You can set `if_doParallel = FALSE`. I will check it later.

**Comment by jinyuanchun** [comment]
thank you for you reply. i try, but also have error.

![image](https://user-images.githubusercontent.com/40689145/192693883-4a9c490b-d3e2-469c-bdca-8ff5a13a08d1.png)
![image](https://user-images.githubusercontent.com/40689145/192693898-0ca3519e-23ea-47a2-b5be-3df34701e9d9.png)

**Comment by multitalk** [comment]
@jinyuanchun I have checked the code and I guess the reason might be that the nrow of `obj@lr_path$lrpairs` is equal to 1, which will lead to the error when calculating the `.lr_distance()`. I have fixed the bug considering the above condition. You can try it now.  If the error still occurs, please feel free to contact me. Thanks again for your reply.

**Comment by multitalk** [comment]
@jinyuanchun Another reason is that the names of cells or spots contain `"-"`. I have added a step to rename the cells or spots in `st_data` and `sc_data`  over `createSpaTalk()` and `dec_celltype` by replacing `"-"` with `"_"` to avoid the error in `dec_cci()` and `dec_cci_all()`. Thanks again

**Comment by hahia** [comment]
> @jinyuanchun Another reason is that the names of cells or spots contain `"-"`. I have added a step to rename the cells or spots in `st_data` and `sc_data` over `createSpaTalk()` and `dec_celltype` by replacing `"-"` with `"_"` to avoid the error in `dec_cci()` and `dec_cci_all()`. Thanks again

Hi, I also meet the problem
![image](https://user-images.githubusercontent.com/49113803/218984074-162bd7a6-55b6-4fba-a0c2-ec7360b712d6.png)

names of st_data and names of celltype:
![image](https://user-images.githubusercontent.com/49113803/218985445-273284eb-6733-4fde-9b12-2636cf878fab.png)


obj@lr_path$lrpairs:
![image](https://user-images.githubusercontent.com/49113803/218984355-569c4295-1044-41db-baa8-4363648895f0.png)

**Comment by multitalk** [comment]
@hahia I guess it might be the names of `obj@meta$rawmeta$cell`. You could paste a `C` to the cellname, e.g., `C111300`, `C30834`, and re-run the codes starting from `createSpaTalk()`

**Comment by hahia** [comment]
> @hahia I guess it might be the names of `obj@meta$rawmeta$cell`. You could paste a `C` to the cellname, e.g., `C111300`, `C30834`, and re-run the codes starting from `createSpaTalk()`

Ok! Problem solved.

**Comment by jinyuanchun** [comment]
thank you



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 02/17/2023 09:31 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ZJUFanLab/SpaTalk] problem: dec_cci and dec_cci_all (Issue #10) |

@hahia I guess it might be the names of ***@***.***$rawmeta$cell. You could paste a C to the cellname, e.g., C111300, C30834, and re-run the codes starting from createSpaTalk()

Ok! Problem solved.

**Comment by liangbolyu** [comment]
Hi here is a question when I use the function dec_cci_all(). I'm doing a simulation to test the method, so I just have 2 cell types and two pathways. But I face the problem here:


![0ecd6912bce00d1f14da4d78e4eb546](https://github.com/ZJUFanLab/SpaTalk/assets/156827043/ef06049a-9184-406d-844b-3c9edc85e50e)

Could you please help me with it? Thank you.
