### ISSUE TITLE
Visulization (cell-cell communications)

### ISSUE THREAD

**Issue by yangfeizZZ** [ZJUFanLab/SpaTalk#12]
Hello 
Would you mind supplying the full code to visualize cell-cell communication
Thand you

**Comment by yangfeizZZ** [comment]
> obj@lrpair[["celltype_sender"]]
 [1] "eL2_3" "eL2_3" "eL6"   "eL6"   "Endo"  "VIP"   "SST"   "SST"   "Smc"   "Smc"   "Micro" "eL5"  
[13] "eL5"   "eL5"   "Reln" 
> obj@lrpair[["celltype_receiver"]]
 [1] "Astro" "Astro" "Astro" "PVALB" "Astro" "eL6"   "PVALB" "eL4"   "Astro" "Astro" "eL2_3" "Astro"
[13] "Astro" "PVALB" "HPC" 

when i run:
> plot_cci_lrpairs(object = obj,celltype_sender = "Endo",celltype_receiver = "eL4",type = "sig")
Error in `[<-`(`*tmp*`, lrpair$ligand[i], lrpair$receptor[i], value = "*") : 
  subscript out of bounds

**Comment by multitalk** [comment]
Thank you, yangfei. This is because there is no LR pairs between `Endo` and `eL4`. I have updated the code to avoid the error by printing the reason.

**Comment by yangfeizZZ** [comment]
> Thank you, yangfei. This is because there is no LR pairs between `Endo` and `eL4`. I have updated the code to avoid the error by printing the reason.

I know,when i run the right cell-cell pairs,the error is :
> plot_cci_lrpairs(object = obj,celltype_sender = "eL2_3",celltype_receiver = "Astro",type = "sig")
Error in plot_cci_lrpairs(object = obj, celltype_sender = "eL2_3", celltype_receiver = "Astro",  : 
  Limited number of ligand-receptor interactions!

**Comment by multitalk** [comment]
This means the heatmap will be one column or one row, so it returns the error. You can consider other visulization.

**Comment by yangfeizZZ** [comment]
> This means the heatmap will be one column or one row, so it returns the error. You can consider other visulization.

Thank you
