### ISSUE TITLE
Visulization (cell-cell communications)

### ISSUE THREAD

**Issue by yangfeizZZ** [ZJUFanLab/SpaTalk#13]
Hello:
would you mind supplying the full code of visulization,such as plot_lr_path or plot_path2gene.I can not plot the simliar figure  as yours.

**Comment by multitalk** [comment]
@yangfeizZZ I have provided the full code of visulization. In fact, I combine the visulization of SpaTalk with AI to generate the figures. You can try using AI to edit the pdf format of SpaTalk visulization to reprocude the result.
