### ISSUE TITLE
Analyze of Spot-based ST without deconvolution

### ISSUE THREAD

**Issue by ZheFrench** [ZJUFanLab/SpaTalk#18]
I don't have single cell associated to my spot based visium data.
I would like to analyze my spot based ST it without deconvolution.
I was wondering if spatalk still can be applied in this situation (setting spot_max_cell to 1), at least in an exploratory mode.

Also when you use deconvolution, you reconstruct a matrix of cells.
From a spot based matrix, you end up with a cell matrix where counts are recomputed thanks to non linear model , right ?

Last question. When you say you apply deconvolution directly ([here](https://github.com/ZJUFanLab/SpaTalk/wiki/Use-other-deconvolution-methods)) over result which is a matrix. What is the format needed?
`obj <- dec_celltype(obj, ..., dec_result = result)`

Rows are cell spot. Columns are cell types. The values are the proportions or pvalues ? 

Update: 
` obj <- dec_celltype(obj, ..., dec_result = result)

Here you can reuse the output from deconvolution method. (in the case you don't have the counts of the sc data)
But in fact you still need to pass sc_data :/ and sc_celltype il also mandatory. Ok for sc_celltype, but for sc_data, it's kind of weird ? Can it be bypassed by reusing the count from the spot ....because you should only use the output file of  the deconvolution, no ? Or do you reuse the sc data from here later ? 
Tks.

**Comment by ZheFrench** [comment]
Also I found a bug in` methods.R  line 317` when you test dec_result colnames to be in the  of sc_celltype$celltype. There is a problem with the parenthesis. As it is done, it converts string into boolean and always send to stop !
```
        if (!all(dec_colname) %in% unique(sc_celltype$celltype)) {
            stop("Celltype name in dec_result must be consistent with the names in scRNA-seq reference!")
        }
```
Proposed solution.
```
        if (!all(dec_colname %in% unique(sc_celltype$celltype))) {
            stop("Celltype name in dec_result must be consistent with the names in scRNA-seq reference!")
        }

```

**Comment by multitalk** [comment]
@ZheFrench Thanks for your feedback. Here is only one situation for Visium data without single-cell reference data, where you need to define the cell type for spot-based data.

```
obj <- createSpaTalk(..., spot_max_cell = 1, celltype) # Define the cell type for each spot
obj <- find_lr_path(object = obj, lrpairs = lrpairs, pathways = pathways)
obj <- dec_cci_all(object = obj)
```
As you said, sc_data is still required for `dec_celltype()` to reconstruct the single-cell ST data if you use `dec_result`, which is a matrix where rows are cell spot, columns are cell types, and the values are the proportions or weights.

Also, I have fixed the proposed bug. Thank you very much.

**Comment by ZheFrench** [comment]
Ok thanks and you set `if_st_is_sc = T` , right ?

**Comment by multitalk** [comment]
If the first colname of `st_meta` is `spot`, then set `if_st_is_sc = F`. If the first colname of `st_meta` is `cell`, then set `if_st_is_sc = T`.

**Comment by ZheFrench** [comment]
So here how do you set st_meta first `col` spot or `cell` ? when you use spot-based but with `spot_max_cell = 1`.
`spot` I guess but i'm not sure it works in this case, I need to test.

```
    obj <- createSpaTalk(st_data = counts,
                         st_meta = areas[,c("spot","x","y")],
                         species = "Human",
                         if_st_is_sc = F,
                         spot_max_cell = 1,
                         celltype = areas[,c("cell_type")]
                        ) 
```

update : yeah that s working. That's pretty cool. Thanks.
