### ISSUE TITLE
Cannot use method plot_path2gene

### ISSUE THREAD

**Issue by XinyeZhao** [ZJUFanLab/SpaTalk#2]
Hi,
Currently I can use all the other functions, but when I try to run plot_path2gene, it shows an error that 
![image](https://user-images.githubusercontent.com/92811944/164581452-444217ef-5514-4222-af42-8c75b534568f.png)
Cna you tell me how to fix this?
Thanks!

**Comment by multitalk** [comment]
Thnaks for your reply, I have fixed this problem. You can try again.

**Comment by XinyeZhao** [comment]
Hi,
Just a follow-up, I still got this issue after updating my codes, can you take a look at it further?
Thanks!

**Comment by multitalk** [comment]
I have tried many datasets and they all return no error
