### ISSUE TITLE
你好 我在使用您的软件时候报错了 请问会是什么原因呢

### ISSUE THREAD

**Issue by ozuoano** [ZJUFanLab/SpaTalk#21]
这是报错信息：
Begin to find LR pairs 
Error in { : task 34 failed - "replacement has 157 rows, data has 1"
Calls: dec_cci -> .get_tf_res_doParallel -> %dopar% -> <Anonymous>
Execution halted
这是我的运行代码：
stRNA <- dec_cci(object = stRNA, 
                   use_n_cores = 10,
                   celltype_sender = 'CD8_T',
                   celltype_receiver = 'Epithelial_cancer')

**Comment by ozuoano** [comment]
其他切片没有报错就是这张切片报错了

**Comment by multitalk** [comment]
请问你是用最新的版本跑的吗？试试不用并行看看报错是啥

**Comment by pillar-github** [comment]
我也有一张ST的数据这样报错，其他还能跑出来。请问是什么问题呢？因为我切片里的细胞点数有1万多，不用并行的话需要跑很久，请问还有其他方法解决吗？谢谢指导！

**Comment by ozuoano** [comment]
> 我也有一张ST的数据这样报错，其他还能跑出来。请问是什么问题呢？因为我切片里的细胞点数有1万多，不用并行的话需要跑很久，请问还有其他方法解决吗？谢谢指导！

我就是慢慢跑的 没啥解决办法
