### ISSUE TITLE
Document Package Dependency 

### ISSUE THREAD

**Issue by boyiguo1** [ZJUFanLab/SpaTalk#23]
Hi,

Thanks for producing this awesome software with clear documentations.

While I was trying to install your package, I realized that your package depends on some other package that is not on CRAN, e.g. `NNLM`.

It would be great if you could document that in your installation instruction. That will help nontechnical users to navigate through the installation process easier.

Thanks!

**Comment by multitalk** [comment]
Thank you very much. I have added the dependent package `NNLM`  according to your suggestion.
