### ISSUE TITLE
r-error-replacement-has-63-row-data-has-1 when changing co_exp_ratio from 0.1 to 0.05

### ISSUE THREAD

**Issue by CherineLee** [ZJUFanLab/SpaTalk#25]
``
Error in `$<-.data.frame`(`*tmp*`, "co_ratio", value = c(C14x13 = 0, C14x14 = 0,  : 
replacement has 63 rows, data has 1
``

A reference: https://www.statology.org/r-error-replacement-has-1-row-data-has-0/

**Comment by multitalk** [comment]
Thanks for your feedback. I have applied this solution to the corresponding scripts.
