### ISSUE TITLE
Error when running dec_celltype

### ISSUE THREAD

**Issue by boyiguo1** [ZJUFanLab/SpaTalk#26]
I am running into the following error message when running `dec_celltype`. Would you mind providing any insights on where this message could come from?

Thank you very much.

```
Generating single-cell data for each spot 
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'rowSums': invalid character indexing
```

**Comment by multitalk** [comment]
Hello, I guess it might be limited gene symbols between `st_data` and `sc_data`. You can check the `length(intersect(rownames(st_data), rownames(sc_data)))`

**Comment by boyiguo1** [comment]
Got it. Thank you very much for your help!
