### ISSUE TITLE
Is it necessary to run dec_celltype for single-cell ST data

### ISSUE THREAD

**Issue by boyiguo1** [ZJUFanLab/SpaTalk#27]
I was going through your tutorial of SpaTalk on single-cell ST data (https://raw.githack.com/ZJUFanLab/SpaTalk/main/vignettes/sc_tutorial.html).

The tutorial still includes a `dec_celltype`. Is this step necessary, or  a copy-paste error?

Thanks!

**Comment by boyiguo1** [comment]
I guess the answer is yes, because `dec_celltype` assigns the cell type to their cells.

**Comment by boyiguo1** [comment]
See solution https://github.com/ZJUFanLab/SpaTalk/issues/18#issuecomment-1283489945.

I wish the author can update the tutorial as well. Thanks!

**Comment by multitalk** [comment]
Thank you for your careful review and feedback. The tutorial of SpaTalk on single-cell ST data is for these without known cell types, where the `dec_celltype` is like a cell-typing process. For these single-cell ST data with known cell types, no need to use `dec_celltype` as stated in #18 .Thanks again.
