### ISSUE TITLE
Takes too much memory and time for entire visium data

### ISSUE THREAD

**Issue by OnkarMulay** [ZJUFanLab/SpaTalk#28]
Hi, 
thanks for your tool

my data is visium
spots = 4k 
genes = 13k
and 250 gb mem is not enough.

needed some help. 
cheers

**Comment by multitalk** [comment]
Thank you for your feedback. I think you can try the following suggestions:
- Set `spot_max_cell = 10` in `createSpaTalk()` for visium data
- Set `if_doParallel = FALSE` in `dec_celltype()`
- Use a small number of cpu cores like `use_n_cores = 4` in `dec_celltype()`
