### ISSUE TITLE
No LR pairs found between any of the cell type

### ISSUE THREAD

**Issue by OnkarMulay** [ZJUFanLab/SpaTalk#29]
Thanks for the tool. I have run the tool with your suggestions on fixing the memory issue. But I get the error message for all the cell types in my dataset:-No LR pairs found between X and Y.

Why is this so? I had run the sub-sampled version of my same data with less genes and less spots and it seems to work well there, but not for entire data.

For the dataset in the tutorial: one weird issue: sometimes the program gives the LR pairs for 2 cell-types, but doesn't give LR pair for the same if I run it on next day. :(

**Comment by multitalk** [comment]
You know there is step of sub-sampling to generate the new single-cell ST data which will affect the inferred the LR pairs. So you can try several times to check the result. Also, I suggest to use all cell types (> 2) for the inference of LR pairs.
