### ISSUE TITLE
Question about benckmark codes for SpaOTsc

### ISSUE THREAD

**Issue by XinyeZhao** [ZJUFanLab/SpaTalk#3]
Hi,
Could you also open source the codes of benchmarking SpaTalk with other cell-cell interaction methods like SpaOTsc? Since I also would like to see how much SpaTalk performs better than SpaOTsc. 
Thanks!

**Comment by multitalk** [comment]
Hello, we have uploaded the codes of running other cell-cell communication methods onto the `script`
