### ISSUE TITLE
Probelm in deconvolution

### ISSUE THREAD

**Issue by biostat0903** [ZJUFanLab/SpaTalk#30]
Dear author, 
Our group hopes to use the Spatalk package. When we analyze the 10x Visium data, the function `dec_celltype` can not work. 
Our code:
````R
obj <- dec_celltype(obj,
                               sc_data = as.matrix(sc_count),
                               sc_celltype = celltype,
                               if_doParallel = T,
                               use_n_cores = N_CORES,
                              dec_result = decon_prop)
````
Error:
````R
Error in { :
  task 14 failed - "error in evaluating the argument 'x' in selecting a method for function 'rowSums':
invalid character indexing"
````
Could you tell me the reason for the error? Thank you!

Best,
Sheng

**Comment by multitalk** [comment]
You can check `length(intersect(rownames(st_data), rownames(sc_data)))`. See #26

**Comment by biostat0903** [comment]
Thanks for your fast reply. 
````R
intersect(rownames(st_data),rownames(sc_data)) %>% length
[1] 9510
 dim(st_data)
[1] 9817 7481
dim(sc_data)
[1] 26733 19311
````
Now, I try to use the intersection between sc_data and st_data to subset the two dataset. 

Best,
Sheng

**Comment by biostat0903** [comment]
When I use the intersection to fit the model. 
I also meet the error:
````R
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'rowSums': invalid character indexing
````

**Comment by multitalk** [comment]
Can you show the `colnames(obj@data$rawdata)[1:10]`, `unique(celltype)` and `decon_prop[1:10, ]`?
`all(rownames(decon_prop) == colnames(obj@data$rawdata))`? Is it TRUE?

**Comment by biostat0903** [comment]
Thanks for your fast reply. 
I sent all my data to your email. When you have time, please help me to check that. 
Best, 
Sheng

**Comment by multitalk** [comment]
The reason is that the inconsistent names of `decon_prop`. I have fixed the bug. Thanks for your feedback.

**Comment by multitalk** [comment]
@biostat0903 The reason of error `invalid character indexing` when doing Parallel in `dec_celltype()` is the generation of `NA` data.frame in generated `newmeta`, which will not occur when `if_doParallel = FALSE`. I have finished `dec_celltype(if_doParallel = FALSE)`  for your data without error. I have fixed this bug and you can have a try with `if_doParallel = TRUE`. Thanks a lot!

**Comment by multitalk** [comment]
![dec_celltype](https://user-images.githubusercontent.com/43984681/219940751-655e5a8c-6407-486a-aebe-34d544eda8b2.png)
