### ISSUE TITLE
Error when running dec_celltype using cell2location method

### ISSUE THREAD

**Issue by Jluo21** [ZJUFanLab/SpaTalk#31]
Dear author,

I got the following error when running the dec_celltype function using cell2location method as follows.
![image](https://user-images.githubusercontent.com/95539498/219096482-43ce511d-8bae-465a-b112-03985264b670.png)

![image](https://user-images.githubusercontent.com/95539498/219095917-22704432-1789-4bb8-a47a-e2a016bcd5fd.png)

Do you have any ideas what is the problem? 
Thanks!

**Comment by multitalk** [comment]
I guess the reason is gap between R and python when using reticulate. You can try the `cell2location` python package to get the results and used `dec_result` in `dec_celltype()` like #30
