### ISSUE TITLE
Find TF and pathway regard to specific LR pairs

### ISSUE THREAD

**Issue by hahia** [ZJUFanLab/SpaTalk#32]
Hi, if I have already found a ligand receptor of interest by other methods (CellChat, CellphoneDB...), how can I find the downstream TF and pathway by spatalk. I don't want to use spatalk to find the LR pairs, but to find TF and pathway regard to specific LR pairs.

**Comment by multitalk** [comment]
Maybe you should manully find the TF and pathway regard to specific LR pairs in the system data.frame `pathways`

**Comment by dongyuanwu** [comment]
Hi,

I have a similar question and would appreciate more detailed information on how to find the pathway of a specific LR pair. Is it enough to check if the receptor name matches either the `src` or `dest` column in the `pathway` dataframe, or are there any additional rules we should consider?

Thank you for your time!
