### ISSUE TITLE
Error "Reference: counts does not contain integers"  when using RCTD deconvolution

### ISSUE THREAD

**Issue by Xue-Ya** [ZJUFanLab/SpaTalk#35]
Dear author,
I got the following error when running the dec_celltype function using the RCTD method.
![image](https://user-images.githubusercontent.com/71007696/230321344-9a749104-4b43-4db6-8ef5-702382c41f2d.png)

Do you have any ideas what the problem is?
Thanks!

**Comment by multitalk** [comment]
`sc_counts` should be integers

**Comment by Xue-Ya** [comment]
Thank you! I may convert my sc_counts to integer. Another problem is that when I use SPOTlight, there is the error "Error: 'spotlight_deconvolution' is not an exported object from 'namespace:SPOTlight'"
After searching, I find the spotlight_deconvolution has changed in https://github.com/MarcElosua/SPOTlight/issues/45#issuecomment-1066991644. Will spatalk update the function?

**Comment by multitalk** [comment]
Hello, you can get the result of deconvolution of RCTD and use `dec_result` in `dec_celltype()` to solve this problem. Please refer to #30 
```
# result must be a matrix
obj <- dec_celltype(obj, ..., dec_result = result)
```
