### ISSUE TITLE
Sudden error in createSpaTalk()

### ISSUE THREAD

**Issue by JakubMlost** [ZJUFanLab/SpaTalk#36]
Hi,

I've been running SpaTalk package successfully for a while but today when I tried to run a script, I noticed that I am not able to create SpaTalk object. Any ideas what might be the cause? 

`> obj_list
[[1]]
An object of class SpaTalk 
Error in (new("standardGeneric", .Data = function (object)  : 
  object 'obj' not found
> traceback()
2: (new("standardGeneric", .Data = function (object) 
   standardGeneric("show"), generic = structure("show", package = "methods"), 
       package = "methods", group = list(), valueClass = character(0), 
       signature = structure("object", simpleOnly = TRUE), default = new("derivedDefaultMethod", 
           .Data = function (object) 
           showDefault(object), target = new("signature", .Data = "ANY", 
               names = "object", package = "methods"), defined = new("signature", 
               .Data = "ANY", names = "object", package = "methods"), 
           generic = structure("show", package = "methods")), skeleton = (new("derivedDefaultMethod", 
           .Data = function (object) 
           showDefault(object), target = new("signature", .Data = "ANY", 
               names = "object", package = "methods"), defined = new("signature", 
               .Data = "ANY", names = "object", package = "methods"), 
           generic = structure("show", package = "methods")))(object)))(new("SpaTalk", 
       data = list(rawdata = new("dgCMatrix", i = c(0L, 3L, 4L, 
       5L, 7L, 8L, 10L, 13L, 14L, 15L, 18L, 20L, 23L, 25L, 27L, 
       31L, 35L, 36L, 41L, 46L, 48L, 49L, 50L, 52L, 59L, 62L, 65L, 
       67L, 68L, 69L, 70L, 72L, 73L, 74L, 77L, 78L, 79L, 80L, 81L, 
       82L, 84L, 87L, 89L, 90L, 92L, 96L, 97L, 104L, 105L, 108L, 
       112L, 113L, 114L, 115L, 116L, 120L, 121L, 124L, 125L, 126L, 
    ...
1: (new("standardGeneric", .Data = function (object) 
   standardGeneric("show"), generic = structure("show", package = "methods"), 
       package = "methods", group = list(), valueClass = character(0), 
       signature = structure("object", simpleOnly = TRUE), default = new("derivedDefaultMethod", 
           .Data = function (object) 
           showDefault(object), target = new("signature", .Data = "ANY", 
               names = "object", package = "methods"), defined = new("signature", 
               .Data = "ANY", names = "object", package = "methods"), 
           generic = structure("show", package = "methods")), skeleton = (new("derivedDefaultMethod", 
           .Data = function (object) 
           showDefault(object), target = new("signature", .Data = "ANY", 
               names = "object", package = "methods"), defined = new("signature", 
               .Data = "ANY", names = "object", package = "methods"), 
           generic = structure("show", package = "methods")))(object)))(new("SpaTalk", 
       data = list(rawdata = new("dgCMatrix", i = c(0L, 3L, 4L, 
       5L, 7L, 8L, 10L, 13L, 14L, 15L, 18L, 20L, 23L, 25L, 27L, 
       31L, 35L, 36L, 41L, 46L, 48L, 49L, 50L, 52L, 59L, 62L, 65L, 
       67L, 68L, 69L, 70L, 72L, 73L, 74L, 77L, 78L, 79L, 80L, 81L, 
       82L, 84L, 87L, 89L, 90L, 92L, 96L, 97L, 104L, 105L, 108L, 
       112L, 113L, 114L, 115L, 116L, 120L, 121L, 124L, 125L, 126L, 
    ...`

**Comment by multitalk** [comment]
![image](https://user-images.githubusercontent.com/43984681/230951301-1c8cfbf6-b39a-4a2b-8784-ad14227908d2.png)

Maybe you can re-install it and try again.
