### ISSUE TITLE
How to get predict CCI results?

### ISSUE THREAD

**Issue by XinyeZhao** [ZJUFanLab/SpaTalk#4]
Hi,

Could you tell me which variable I should use if I want to get the predicting results of the cell-cell interactions from the R obj? I think all the functions in this repository is for plotting the results, but I would like to get the data.

Thanks!

**Comment by multitalk** [comment]
You can use `obj@lrpair` to get the inferred LR pairs, `obj@tf` to get the inferred TFs of receptors, and `obj@lr_path` to get the inferred lrpairs and pathways.
