### ISSUE TITLE
Seurat 5.0.1 Compatibility Issues

### ISSUE THREAD

**Issue by EJXie** [ZJUFanLab/SpaTalk#40]
Hi there,

In the tutorial (https://raw.githack.com/multitalk/awesome-cell-cell-communication/main/method/spot_tutorial.html), when running the code with **Seurat** Version **5.0.1** for decoding cell-type decomposition (code shown below), there was an error message of " **Error in .normalize_data(st_data) :  no slot of name "data" for this object of class "Assay5"** ". 

After changing the **Seurat** Version to **4.4.0**, the error is sorted.

It will be great if you can look into it.

Thank you very much!

# decode the cell-type composition
obj <- dec_celltype(object = obj,
                    sc_data = as.matrix(starmap_data),
                    sc_celltype = starmap_meta$celltype)

**Comment by multitalk** [comment]
Thanks for your feedback. We are working on the compatibility with Seurat 5.

**Comment by alexanderchang1** [comment]
Has there been any update on fixing this issue?

**Comment by EJXie** [comment]
> Has there been any update on fixing this issue?

Hi Chang,

I have checked it again, it does not seem to be fixed yet

**Comment by multitalk** [comment]
Hello @EJXie @alexanderchang1, now it is compatible with Seurat 5. You can try again.
