### ISSUE TITLE
Question about codes for benchmark metrics

### ISSUE THREAD

**Issue by EronHou** [ZJUFanLab/SpaTalk#5]
Hi,
Could you open source the codes of computing log-p and co-expression percent for all possible sender-receiver pairs? From the current code, I can only compute log-p for one specific sender-receiver pairs, which is not sufficient to reproduce results shown in Fig 2 d-e.
Thanks!

**Comment by multitalk** [comment]
For the co-expression percent, you can use the `obj@cellpair`, which shows all cell-cell pairs from senders to receivers, and you can use the expressed ligand and receptor among these cell-cell pairs to calculate the co-expression percent.
