### ISSUE TITLE
problem plot_ccdist()

### ISSUE THREAD

**Issue by jinyuanchun** [ZJUFanLab/SpaTalk#7]
i test plot_ccdist()
`# Point plot with spatial distribution of celltype_sender and celltype_receiver   
plot_ccdist(object = obj,
            celltype_sender = 'eL5',
            celltype_receiver = 'Astro',            
            size = 2,
            arrow_length = 0.1)`
problem is : 
`Error in `f()`:
! Insufficient values in manual scale. 3 needed but only 1 provided.`

**Comment by multitalk** [comment]
Is obj generated from single-cell or spot-based ST?

**Comment by jinyuanchun** [comment]
i use you demo as a test. it spot-based ST

**Comment by yangfeizZZ** [comment]
I have the same problem

**Comment by multitalk** [comment]
Thanks for your feedback, I have fixed the bug and now it works well. You can try again. @jinyuanchun @yangfeizZZ

**Comment by yangfeizZZ** [comment]
> Thanks for your feedback, I have fixed the bug and now it works well. You can try again. @jinyuanchun @yangfeizZZ

I have a problem in a  new issue.Thank you
