### ISSUE TITLE
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) :    invalid character indexing

### ISSUE THREAD

**Issue by ZheFrench** [ZJUFanLab/SpaTalk#9]
Hi guys,

Been stuck with this error all this morning.

`Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) :    invalid character indexing  
Calls : find_lr_path ... callGeneric -> eval -> eval -> [ -> [ -> subCsp_cols -> intI`

I finally found why, so I prefer to share it with you if someone meet the same problem then he could easily find the solution here.

The error occurs because I defined in `celltype` argument NA values via in ` areas$ground_truth` ...but the `createSpaTalk` object was well created. So maybe you could add some check to avoid this error when NA.

```

obj <- createSpaTalk(st_data = counts,
                     st_meta = areas[,c("cell","x","y")],
                     species = "Human",
                     if_st_is_sc = T,
                     spot_max_cell = 1,
                     celltype = areas$ground_truth)

obj <- find_lr_path(object = obj , lrpairs = lrpairs, pathways = pathways,if_doParallel = T,use_n_cores=8)

```

**Comment by multitalk** [comment]
Thank you for sharing！
